"""Original Deb/Visha seed. 1850 Calcutta. Adult characters. Non-graphic restrained romance."""

BIBLE = {
    "premise": "Calcutta, 1850. Deb (26) and Visha (24) exchange secret notes. Attraction grows slowly. A family marriage discussion forms around Visha. Neither says what they want.",
    "setting": "Company-era Calcutta, 1850. Courtyards, monsoon, lamp-light. Notes passed in secret, not machines.",
    "year": 1850,
    "timeline_anchors": ["আষাঢ় monsoon", "a family proposal conversation", "an almost-meeting at the ghat"],
    "locations": [
        "Visha's family courtyard in north Calcutta",
        "Deb's rented room near a merchant office",
        "the river ghat at dusk",
        "ink and folded paper",
    ],
    "literary_direction": "emotional restraint, longing, family pressure, pride, vulnerability, quiet care; original 1850 Bengal; do not copy any existing author",
    "characters": [
        {
            "name": "Deb",
            "age": 26,
            "pronouns": "he/him",
            "role": "lead",
            "personality": {"restraint": "high", "pride": "defensive", "care": "practical"},
            "speech_style": {"length": "medium", "directness": "delayed", "slang": "none"},
            "goals": ["to remain in her days without making a scene", "not to look foolish"],
            "fears": ["she will choose duty", "he waited too long to be clear"],
            "secrets": ["he declined a clerk's posting outside the city so he would not leave this year"],
            "backstory": "Clerk in a merchant house. Modest standing. Writes more than he speaks.",
        },
        {
            "name": "Visha",
            "age": 24,
            "pronouns": "she/her",
            "role": "lead",
            "personality": {"restraint": "high", "pride": "quiet", "humor": "dry"},
            "speech_style": {"length": "short", "questions": "oblique", "slang": "none"},
            "goals": ["to be chosen without having to ask", "not to hurt her parents"],
            "fears": ["becoming a family disappointment", "wanting someone the house will not accept"],
            "secrets": ["she has already imagined a life that does not include the proposed match"],
            "backstory": "Lives with parents. Reads more than she is allowed to show.",
        },
    ],
    "social_context": "Respectable Bengali household; reputation; pishi and marriage talk; difference of standing.",
}

THREADS = [
    {
        "name": "Unspoken attachment",
        "description": "Neither has directly confessed.",
        "stakes": "Politeness may outlast the chance.",
        "severity": 45,
    },
    {
        "name": "Family marriage pressure",
        "description": "Visha's family is beginning to discuss a suitable match.",
        "stakes": "A viewing could close the door before either speaks.",
        "severity": 30,
    },
]

CHAPTERS = [
    {
        "n": 1,
        "title": "প্রথম কথা",
        "closing": "কেউ পুরোপুরি বলেনি কেন লিখল।",
        "objective": "First meaningful encounter",
        "emotional_objective": "curiosity",
        "escalation_target": 24,
        "messages": [
            {"kind": "scene_marker", "body": "আষাঢ়, সন্ধ্যা · প্রদীপ জ্বালা"},
            {"speaker": "Deb", "body": "সেদিন যে গ্রন্থের কথা বলেছিলে… নামটা মনে নেই।"},
            {"speaker": "Visha", "body": "কোনখানি? বৃষ্টির দিনে উঠোনে?"},
            {"speaker": "Deb", "body": "হ্যাঁ। তুমি বলেছিলে শেষ পাতা পড়ে আর নিদ্রা হয়নি।"},
            {"speaker": "Visha", "body": "ও। সে ঘরের ভিতরের কথা। বাইরে শান্ত। ভিতরে সব উল্টেপাল্টে।"},
            {"speaker": "Deb", "body": "তোমার মনে হয় আমাদের নগরটাও সেরকম?"},
            {"speaker": "Visha", "body": "কলকাতা? দিনে ঘাটের কোলাহল, রাতে মনে হয় কেউ অপেক্ষা করছে।"},
            {"speaker": "Deb", "body": "কেউ?"},
            {"speaker": "Visha", "body": "কেউ না। কথা প্রসঙ্গে।"},
            {"speaker": "Deb", "body": "আচ্ছা।"},
            {"kind": "scene_marker", "body": "রাত্রে, কালি শুকোয়নি"},
            {"speaker": "Deb", "body": "রাত্রে নিদ্রা হয়?"},
            {"speaker": "Visha", "body": "হয়। হয় না। তোমার?"},
            {"speaker": "Deb", "body": "আজ হয়নি। তাই লিখলাম।"},
        ],
    },
    {
        "n": 2,
        "title": "জানার ইচ্ছে",
        "closing": "বৃষ্টি থামলেও কথা থামেনি।",
        "objective": "Curiosity",
        "emotional_objective": "curiosity",
        "escalation_target": 36,
        "messages": [
            {"kind": "scene_marker", "body": "সোমবার, রাত্রি · বৃষ্টি"},
            {"speaker": "Visha", "body": "প্রদীপ দেখে মনে হল লিখি। ভুল হলে ছিঁড়ে ফেলো।"},
            {"speaker": "Deb", "body": "ছিঁড়ব না। বলো।"},
            {"speaker": "Visha", "body": "তোমার জানালার দিকটা কি ভিজছে? এপাশে নালা উপচেছে।"},
            {"speaker": "Deb", "body": "ভিজছে। মা বলছেন কাল কাপড় শুকোবে না। আমি বলছি এখন সে চিন্তা নয়।"},
            {"speaker": "Visha", "body": "এখন কোন চিন্তা?"},
            {"speaker": "Deb", "body": "কেউ জেগে আছে কিনা। অযথা।"},
            {"speaker": "Visha", "body": "অযথা না। আমি জেগে আছি।"},
            {"speaker": "Deb", "body": "কাছারির চাপ?"},
            {"speaker": "Visha", "body": "কাজ তো সকালেও থাকে। রাতে অন্য কিছু থাকে। নাম দেওয়া যায় না।"},
            {"speaker": "Deb", "body": "নাম না দিলেও চেনা যায় কখনো কখনো।"},
            {"speaker": "Visha", "body": "তুমি চেনাও?"},
            {"speaker": "Deb", "body": "আজ না। আজ শুধু বৃষ্টি।"},
        ],
    },
    {
        "n": 3,
        "title": "কাছাকাছি",
        "closing": "সে শুনেছিল। সেটাই যথেষ্ট ছিল।",
        "objective": "Emotional connection",
        "emotional_objective": "involvement",
        "escalation_target": 48,
        "messages": [
            {"kind": "scene_marker", "body": "বুধবার, রাত্রি"},
            {"speaker": "Visha", "body": "বাবা আজ রাতে চুপচাপ ছিলেন। প্রদীপ জ্বলছিল। কেউ পড়ছিল না।"},
            {"speaker": "Deb", "body": "মন খারাপ?"},
            {"speaker": "Visha", "body": "বোঝা যায় না। আমাদের বাড়িতে মন খারাপ মানেই অন্য বিষয় নিয়ে কথা বলা।"},
            {"speaker": "Deb", "body": "তুমি জিজ্ঞেস করোনি।"},
            {"speaker": "Visha", "body": "করলে উত্তর আসত অন্য প্রশ্নের। যেমন, মেয়ের বয়স হয়ে গেছে।"},
            {"speaker": "Deb", "body": "চব্বিশ। সেটা বয়স হয়ে যাওয়া নয়।"},
            {"speaker": "Visha", "body": "বাড়ির হিসেবে হয়ে যায়।"},
            {"speaker": "Deb", "body": "আমি হিসেব করি না।"},
            {"speaker": "Visha", "body": "তুমি বাড়িতে থাকো না বলে।"},
            {"speaker": "Deb", "body": "থাকি না। তবু মায়ের চিঠি আসে। আমি উত্তর ফাঁকি দিই। সেটা সাহস নয়।"},
            {"speaker": "Visha", "body": "আজ ফাঁকি দিয়ো না। আমাকেও দিয়ো না।"},
            {"speaker": "Deb", "body": "দিচ্ছি না। লেখো, পড়ছি।"},
            {"speaker": "Visha", "body": "আর কিছু নেই। শুধু কেউ শুনুক লেগেছিল।"},
        ],
    },
    {
        "n": 4,
        "title": "বাড়ির ছায়া",
        "closing": "নামটা সে মুখে আনেনি। তবু ঘর ভারী হয়েছিল।",
        "objective": "Social obstacle appears",
        "emotional_objective": "conflict",
        "escalation_target": 58,
        "messages": [
            {"kind": "scene_marker", "body": "শুক্রবার, সন্ধ্যা"},
            {"speaker": "Visha", "body": "পিসি এসেছিলেন। চা, মিষ্টি, তারপর সেই সুর।"},
            {"speaker": "Deb", "body": "কোন সুর?"},
            {"speaker": "Visha", "body": "ভালো ছেলে। চাকরি আছে। কলকাতাতেই। দেখা করে নিলে ক্ষতি কী।"},
            {"speaker": "Deb", "body": "তুমি কী বললে?"},
            {"speaker": "Visha", "body": "হাসলাম। আমাদের বাড়িতে হাসলে মানে রাজি না। কিন্তু না-ও না।"},
            {"speaker": "Deb", "body": "বিশা।"},
            {"speaker": "Visha", "body": "হ্যাঁ।"},
            {"speaker": "Deb", "body": "নামটা বলোনি।"},
            {"speaker": "Visha", "body": "নাম জানি না। জানতেও চাইনি। পিসি যেভাবে বলেন, মানুষটা যেন খাতা।"},
            {"speaker": "Deb", "body": "খাতা পূরণ করতে হয় না তোমাকে।"},
            {"speaker": "Visha", "body": "সহজ করে বললে সব সহজ হয়ে যায় না।"},
            {"kind": "scene_marker", "body": "রাত্রি"},
            {"speaker": "Visha", "body": "তুমি রাগ করোনি তো?"},
            {"speaker": "Deb", "body": "রাগের অধিকার আমার নেই। চুপ থাকারও কোনো মানে হয় না। তাই লিখছি।"},
        ],
    },
    {
        "n": 5,
        "title": "নিঃশব্দ ঘনিষ্ঠতা",
        "closing": "দেখা হয়নি। অপেক্ষাটা থেকে গেছে।",
        "objective": "Growing intimacy",
        "emotional_objective": "intimacy",
        "escalation_target": 66,
        "messages": [
            {"kind": "scene_marker", "body": "রবিবার, দুপুর"},
            {"speaker": "Deb", "body": "ঘাটে। বিকেলে। যদি পারো। শুধু দাঁড়ানো। আর কিছু না।"},
            {"speaker": "Visha", "body": "ঘাটের নাম করে অন্য কথা আসে পরে। জানো তো।"},
            {"speaker": "Deb", "body": "আসবে না জেনেও ডাকছি। সেটাও জানো।"},
            {"speaker": "Visha", "body": "আসব বলেই ভাবছি। মা যদি জিজ্ঞেস করেন কোথায়—"},
            {"speaker": "Deb", "body": "বলো মন্দির। আমি একটা নাম বলে দেব।"},
            {"kind": "scene_marker", "body": "বিকেল, জোয়ারের হাওয়া"},
            {"speaker": "Visha", "body": "আসতে পারছি না। কাকিমা চলে এসেছেন। এখন বেরোলে সব প্রশ্ন।"},
            {"speaker": "Deb", "body": "ঠিক আছে।"},
            {"speaker": "Visha", "body": "রাগ করো। রাগ না করলে মনে হবে তোমার কিছু যায় আসে না।"},
            {"speaker": "Deb", "body": "যা যায় আসে। তাই দাঁড়িয়ে আছি এখনো। যাব না বলে নয়। একটু দাঁড়াই।"},
            {"speaker": "Visha", "body": "ভেজা সিঁড়িতে বসো না।"},
            {"speaker": "Deb", "body": "বসিনি। কথাটা পড়েই গেলাম।"},
            {"speaker": "Visha", "body": "আমিও যেতে চেয়েছিলাম। এটা বিশ্বাস করো।"},
        ],
    },
    {
        "n": 6,
        "title": "লুকোনো টান",
        "closing": "সত্যিটা অন্য মুখে এসে পৌঁছাল।",
        "objective": "Hidden conflict revealed",
        "emotional_objective": "conflict",
        "escalation_target": 76,
        "messages": [
            {"kind": "scene_marker", "body": "মঙ্গলবার, রাত্রি"},
            {"speaker": "Deb", "body": "হরি বলেছে কিছু। আমি জিজ্ঞেস করিনি। সে বলেছেই।"},
            {"speaker": "Visha", "body": "কী?"},
            {"speaker": "Deb", "body": "তোমাদের বাড়িতে একটা দেখা হওয়ার কথা। শিগগির।"},
            {"speaker": "Visha", "body": "হরির মুখে কথা আসে আগে। পরে সত্যি।"},
            {"speaker": "Deb", "body": "এবার কোনটা?"},
            {"speaker": "Visha", "body": "কথা আছে। আমি রাজি হইনি। রাজি না হওয়া আর থামানো এক নয়। জানো।"},
            {"speaker": "Deb", "body": "আমাকে বলোনি।"},
            {"speaker": "Visha", "body": "বললে তুমি দূরে সরে যেতে। আর না বললে তুমি ভাববে আমি লুকোচ্ছি। দুটোই সত্যি হয়ে যাচ্ছিল।"},
            {"speaker": "Deb", "body": "আমি সরে যাইনি। এখনো যাইনি।"},
            {"speaker": "Visha", "body": "যাবে?"},
            {"speaker": "Deb", "body": "প্রশ্নটা তোমার নয় আমারও। তাই উত্তর তাড়াতাড়ি দিচ্ছি না।"},
            {"speaker": "Visha", "body": "দিয়ো না। শুধু চলে যেয়ো না চুপ করে।"},
        ],
    },
    {
        "n": 7,
        "title": "দূরত্ব",
        "closing": "পোড়ানো পাতাটাই সব বলেছিল।",
        "objective": "Misunderstanding / separation",
        "emotional_objective": "separation",
        "escalation_target": 68,
        "messages": [
            {"kind": "scene_marker", "body": "বৃহস্পতিবার, প্রভাত"},
            {"speaker": "Visha", "body": "সুপ্রভাত।"},
            {"speaker": "Deb", "body": "হ্যাঁ।"},
            {"kind": "scene_marker", "body": "দুপুর"},
            {"speaker": "Visha", "body": "ব্যস্ত?"},
            {"speaker": "Deb", "body": "হ্যাঁ।"},
            {"kind": "scene_marker", "body": "রাত্রি"},
            {"speaker": "Visha", "body": "তিনটে হ্যাঁ। এটাও একরকম উত্তর।"},
            {"speaker": "Deb", "body": "আমি খারাপ করে ফেলছি। জানি। কথা খুঁজে পাচ্ছি না যা অন্যায় হবে না।"},
            {"speaker": "Visha", "body": "অন্যায় হবে না এমন কথা কি খুব দরকার?"},
            {"speaker": "Deb", "kind": "deleted", "body": "এক পাতা পুড়িয়ে ফেলা হয়েছে"},
            {"speaker": "Visha", "body": "যা পুড়িয়েছ, সেটাই বোধহয় লেখার কথা ছিল।"},
            {"speaker": "Deb", "body": "লিখলে আর ফেরত নেওয়া যায় না। আজ পারি না।"},
            {"speaker": "Visha", "body": "আচ্ছা। তাহলে আজ নয়।"},
        ],
    },
    {
        "n": 8,
        "title": "ফিরে আসা",
        "closing": "আবার বৃষ্টি। আবার একই দুটো নাম।",
        "objective": "Reconnection",
        "emotional_objective": "reconnection",
        "escalation_target": 80,
        "messages": [
            {"kind": "scene_marker", "body": "শনিবার, রাত্রি · বৃষ্টি"},
            {"speaker": "Deb", "body": "বিশা। তুমি ঠিক আছো?"},
            {"speaker": "Visha", "body": "আছি। তুমি?"},
            {"speaker": "Deb", "body": "না। তাই জিজ্ঞেস করলাম।"},
            {"speaker": "Visha", "body": "সেদিন পুড়িয়েছিলে কী?"},
            {"speaker": "Deb", "body": "লিখেছিলাম—আমি চাই তুমি সেই দেখাটাতে না যাও। তারপর মনে হল, চাওয়াটা তোমার সিদ্ধান্তের ওপর চাপ।"},
            {"speaker": "Visha", "body": "চাপ আর সত্যি—দুটো আলাদা। আমি সত্যিটা শুনতে চেয়েছিলাম।"},
            {"speaker": "Deb", "body": "তাহলে শোনো। আমি চাই তুমি না যাও। আর চাই তুমি গেলেও আমাকে মিথ্যে না বলো।"},
            {"speaker": "Visha", "body": "যাইনি এখনো। কাল পিসি আবার আসবেন। মা চুপ করে থাকবেন। সেটাই ভারী।"},
            {"speaker": "Deb", "body": "আমি এপাশে আছি। সমাধান হাতে নেই। এপাশে আছি শুধু।"},
            {"speaker": "Visha", "body": "শুধুটাই দরকার ছিল।"},
        ],
    },
    {
        "n": 9,
        "title": "পছন্দের মুহূর্ত",
        "closing": "কালকের বৈঠক। আজকের একটি প্রশ্ন।",
        "objective": "Major choice",
        "emotional_objective": "climax",
        "escalation_target": 88,
        "messages": [
            {"kind": "scene_marker", "body": "রবিবার, প্রভাত"},
            {"speaker": "Visha", "body": "কাল সন্ধ্যায় বাড়িতে লোক আসবে। মা বলেছেন শুধু দেখা। শুধু কখনো শুধু থাকে না।"},
            {"speaker": "Deb", "body": "তুমি কী করতে চাও? বাড়ির কথা বাদ দিয়ে। একবার।"},
            {"speaker": "Visha", "body": "চাই যেন কেউ আমার হয়ে সিদ্ধান্ত না নেয়। আর চাই তোমাকে বলতে যে আমি ভয় পাচ্ছি।"},
            {"speaker": "Deb", "body": "ভয় পাওয়ার অধিকার আছে। পালানোরও। থাকারও।"},
            {"speaker": "Visha", "body": "তুমি কি থাকবে? বৈঠকে নয়। পরে। যদি আমি না বলি হ্যাঁ। যদি বাড়ি রাগ করে।"},
            {"speaker": "Deb", "body": "থাকব। এটা প্রতিশ্রুতি। নাটক নয়।"},
            {"speaker": "Visha", "body": "প্রতিশ্রুতি ভারী শব্দ।"},
            {"speaker": "Deb", "body": "তাই ব্যবহার করলাম। হালকা শব্দ দিয়ে আর কাজ হচ্ছিল না।"},
            {"speaker": "Visha", "body": "কালকের আগে আজ রাতে লিখো। আমিও লিখব। নিদ্রা হোক বা না হোক।"},
            {"speaker": "Deb", "body": "লিখব। তুমি একা সিদ্ধান্ত নিয়ো না রাতের অন্ধকারে।"},
        ],
    },
    {
        "n": 10,
        "title": "যা বলা হয়নি",
        "closing": "কথাটা সে বলেনি। কিন্তু দুজনেই বুঝেছিল।",
        "objective": "Climax and quiet consequence",
        "emotional_objective": "climax",
        "escalation_target": 92,
        "messages": [
            {"kind": "scene_marker", "body": "সোমবার, রাত্রি"},
            {"speaker": "Visha", "body": "বললাম যাব না। মা কেঁদেছিলেন না। শুধু থালাটা জোরে রেখেছিলেন। সেটাই কান্না।"},
            {"speaker": "Deb", "body": "তুমি কেমন আছো?"},
            {"speaker": "Visha", "body": "দোষী। হালকা। দুটো একসাথে। তুমি কি খুশি?"},
            {"speaker": "Deb", "body": "খুশি শব্দটা ছোট। আমি নিশ্চিন্ত নই। কিন্তু কাছে আছি।"},
            {"speaker": "Visha", "body": "কাছে মানে কী, দেব? এখন আর ঘুরিয়ে লেখার দিন নেই।"},
            {"speaker": "Deb", "body": "মানে আমি তোমাকে হারাতে চাইনি। চাই না। আরও পরিষ্কার করতে গেলে যে শব্দটা আসে, সেটা আজ রাতেও ভারী।"},
            {"speaker": "Visha", "body": "তাহলে সেটা আজ না হয় না-ই বলো। শুধু থাকো। আমিও থাকছি।"},
            {"speaker": "Deb", "body": "আছি। কাল সকালেও থাকব। বৃষ্টি হলে খবর দিয়ো। না হলেও দিয়ো।"},
            {"speaker": "Visha", "body": "দিব। নিদ্রা হলেও কাগজটা কাছে থাকবে।"},
            {"kind": "scene_marker", "body": "মঙ্গলবার, ভোর"},
            {"speaker": "Visha", "body": "ঘুম হয়নি। হয়নি বলে খারাপও লাগছে না।"},
            {"speaker": "Deb", "body": "আমারও না। নগরটা আজ একটু কম উল্টেপাল্টে মনে হচ্ছে।"},
        ],
    },
]
